repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # Versão fixa do Black
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Versão do isort
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Versão do flake8
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Conjunto de hooks úteis
    hooks:
      - id: end-of-file-fixer        # Garante linha em branco no final dos arquivos
      - id: trailing-whitespace      # Remove espaços em branco no fim de linhas
      - id: check-added-large-files  # Previne commit de arquivos grandes sem querer
